package hibernate_dse;
// Generated 03/07/2024 10:42:49 PM by Hibernate Tools 4.3.1



/**
 * Estudiantes generated by hbm2java
 */
public class Estudiantes  implements java.io.Serializable {


     private int codigo;
     private String nombre;
     private String apellido;
     private String direccion;
     private String email;
     private String estado;

    public Estudiantes() {
    }

    public Estudiantes(int codigo, String nombre, String apellido, String direccion, String email, String estado) {
       this.codigo = codigo;
       this.nombre = nombre;
       this.apellido = apellido;
       this.direccion = direccion;
       this.email = email;
       this.estado = estado;
    }
   
    public int getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


